package log

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"testing"
)

// Create a new temporary file for the test use.
// The file is automatically removed when the test and all its subtests complete.
// The filename is generated by taking pattern and adding a random string to the end.
// If pattern includes a "*", the random string replaces the last "*".
// The file is created with mode 0o600 (before umask).
func tempFile(t *testing.T, pattern string) (*os.File, error) {
	t.Helper()
	dir := t.TempDir()
	f, err := os.CreateTemp(dir, pattern)
	return f, err
}

func openFile(name string) (file *os.File, size int64, err error) {
	f, err := os.OpenFile(name, os.O_RDWR|os.O_CREATE|os.O_APPEND, 0644)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to open %s: %+v", name, err)
	}
	fi, err := f.Stat()
	if err != nil {
		return nil, 0, fmt.Errorf("failed to get file info of %s: %+v", name, err)
	}
	return f, fi.Size(), nil
}

func copyToDir(name string, dstDir string) error {
	f, err := os.Open(name)
	if err != nil {
		return fmt.Errorf("failed to open %s: %+v", name, err)
	}
	path := fmt.Sprintf("%s/%s", dstDir, filepath.Base(f.Name()))
	tempf, err := os.OpenFile(path, os.O_CREATE|os.O_TRUNC|os.O_RDWR, 0644)
	if err != nil {
		return fmt.Errorf("failed to open %s: %+v\n", path, err)
	}
	if _, err = io.Copy(tempf, f); err != nil {
		return fmt.Errorf("failed to cp %s to %s: %+v\n", f.Name(), path, err)
	}
	return nil
}
