package log

import (
	"fmt"
	"os"
	"testing"
)

// Create a new temporary file for the test use.
// The file is automatically removed when the test and all its subtests complete.
// The filename is generated by taking pattern and adding a random string to the end.
// If pattern includes a "*", the random string replaces the last "*".
// The file is created with mode 0o600 (before umask).
func tempFile(t *testing.T, pattern string) (*os.File, error) {
	t.Helper()
	dir := t.TempDir()
	f, err := os.CreateTemp(dir, pattern)
	return f, err
}

func openFile(name string) (file *os.File, size int64, err error) {
	f, err := os.OpenFile(name, os.O_RDWR|os.O_CREATE|os.O_APPEND, 0644)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to open %s: %+v", name, err)
	}
	fi, err := f.Stat()
	if err != nil {
		return nil, 0, fmt.Errorf("failed to get file info of %s: %+v", name, err)
	}
	return f, fi.Size(), nil
}
